stages:
  - build_kinetic
  - build_lunar
  - build_melodic
  - test

run-build:
  image: ros:kinetic-perception-xenial
  stage: build_kinetic
  before_script:
  - source /opt/ros/kinetic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.13-0v5 libcppunit-dev
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make

run-build:
  image: ros:lunar-perception-xenial
  stage: build_lunar
  before_script:
  - source /opt/ros/lunar/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.13-0v5 libcppunit-dev
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make

run-build:
  image: ros:melodic-perception-bionic
  stage: build_melodic
  before_script:
  - source /opt/ros/melodic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.13-0v5 libcppunit-dev 
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make

run-test:
  stage: test
  script :
    - cd ~/ros_ws
    - make test
