stages:
  - build
  - test

run-build-kinetic:
  image: ros:kinetic-perception-xenial
  stage: build
  before_script:
  - source /opt/ros/kinetic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.13-0v5 libcppunit-dev
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make
    
run-test-kinetic:
  stage: test
  image: ros:kinetic-perception-bionic
  before_script:
  - source /opt/ros/kinetic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.14-0 libcppunit-dev
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make run_tests
    
run-test-melodic:
  stage: test
  image: ros:melodic-perception-bionic
  before_script:
  - source /opt/ros/melodic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.14-0 libcppunit-dev libtinyxml-dev
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make run_tests
    
run-build-melodic:
  image: ros:melodic-perception-bionic
  stage: build
  before_script:
  - source /opt/ros/melodic/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.14-0 libcppunit-dev libtinyxml-dev
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make

run-build-lunar:
  image: ros:lunar-perception-xenial
  stage: build
  allow_failure : true
  before_script:
  - source /opt/ros/lunar/setup.bash
  - apt-get update -qq && apt-get install -y libcppunit-1.13-0v5 libcppunit-dev libtinyxml-dev
  script:
    - mkdir -p ~/ros_ws/src
    - cd ~/ros_ws
    - catkin_make
    - cd src
    - cp -r /builds/DavidTrimoulet/ontologenius .
    - cd ..
    - catkin_make
